from __future__ import annotations

import actionlineage


def test_public_api_exports_stable_core_symbols() -> None:
    expected_exports = {
        "EventEnvelope",
        "EventType",
        "ConsoleContextError",
        "ConsoleExport",
        "ConsoleNote",
        "ConsoleSavedView",
        "DEFAULT_DATABASE_PATH",
        "DEFAULT_JOURNAL_PATH",
        "AwsCloudTrailObserver",
        "AzureActivityObserver",
        "EvidenceRecord",
        "EvidenceLink",
        "EvidenceNormalizer",
        "EvidenceSourceKind",
        "GroupExplanation",
        "JournalAnchor",
        "JournalAnchorLogEntry",
        "JournalSegmentManifest",
        "POSTGRES_DEFAULT_TABLE",
        "POSTGRES_PROJECTION_SCHEMA_VERSION",
        "NormalizedAction",
        "NormalizedResource",
        "PostgresProjectionReader",
        "PostgresRebuildResult",
        "ToolIdentity",
        "append_journal_anchor_log",
        "create_journal_anchor",
        "export_verified_prefix",
        "load_journal_anchor_log",
        "LocalJournal",
        "LineageContract",
        "ContractDetectionRequirement",
        "ContractEvidenceLinkRequirement",
        "ContractLatencyRequirement",
        "DetectionRuleLoadError",
        "SequenceRule",
        "RuleExplanation",
        "ReplayCase",
        "MutationStrategy",
        "ScenarioManifest",
        "FilesystemObserver",
        "GcpAuditLogObserver",
        "HttpResponseReadbackObserver",
        "HttpServerLogObserver",
        "KubernetesAuditObserver",
        "MockHttpReceiverObserver",
        "ObserverOutcome",
        "SqliteReadbackObserver",
        "WebhookReceiptObserver",
        "ExportProfile",
        "FileSink",
        "OpenTelemetrySpanSink",
        "OpenTelemetryExporterUnavailable",
        "ServiceRole",
        "ServiceCapability",
        "ServiceRuntimeConfigError",
        "StaticTokenAuthenticator",
        "ProjectionStateCode",
        "ProjectionStateError",
        "VerifiedPostgresProjectionSnapshot",
        "VerifiedProjectionSnapshot",
        "StageExplanation",
        "import_evidence_batch",
        "parse_event",
        "postgres_schema_statements",
        "serialize_event",
        "verify_journal",
        "verify_journal_anchor",
        "verify_journal_anchor_log",
        "query_timeline",
        "verify_projection_state",
        "verify_postgres_projection_state",
        "rebuild_postgres_projection",
        "render_console_html",
        "export_incident",
        "validate_contract",
        "load_contract",
        "load_sequence_rules",
        "write_contract_template",
        "evaluate_sequence_rule",
        "explain_sequence_rule",
        "sequence_rule_from_dict",
        "sequence_rule_to_dict",
        "score_detection_robustness",
        "build_mutation_cases",
        "minimize_counterexample",
        "verify_observation",
        "export_events",
        "otel_attributes_for_event",
        "otel_attributes_for_redacted_event",
        "check_local_health",
        "console_context_from_dict",
        "load_console_context",
        "create_service_app_from_env",
        "require_capability",
        "write_console",
        "assess_event_compatibility",
        "built_in_sequence_rules",
    }

    assert expected_exports <= set(actionlineage.__all__)
    for export in expected_exports:
        assert getattr(actionlineage, export) is not None
