"""Domain primitives for ActionLineage evidence."""

from actionlineage.domain.events import (
    CANONICALIZATION_VERSION,
    SPEC_VERSION,
    Causality,
    Classification,
    Correlation,
    CorroborationType,
    EventEnvelope,
    EventType,
    EvidenceLink,
    EvidenceRelationship,
    IntegrityMetadata,
    Principal,
    PrincipalType,
    ResourceType,
    Sensitivity,
    Source,
    TrustLevel,
    VerificationStatus,
)
from actionlineage.domain.ids import FixedIdGenerator, IdGenerator, PrefixedUuidGenerator
from actionlineage.domain.redaction import (
    CaptureMetadata,
    RedactionError,
    RedactionPolicy,
    capture_bytes,
    capture_string,
)
from actionlineage.domain.serialization import (
    deterministic_json_bytes,
    event_from_json,
    event_to_dict,
    parse_event,
    serialize_event,
    serialize_event_for_persistence,
)
from actionlineage.domain.time import Clock, FixedClock, SystemClock

__all__ = [
    "CANONICALIZATION_VERSION",
    "SPEC_VERSION",
    "CaptureMetadata",
    "Causality",
    "Classification",
    "Clock",
    "Correlation",
    "CorroborationType",
    "EventEnvelope",
    "EventType",
    "EvidenceLink",
    "EvidenceRelationship",
    "FixedClock",
    "FixedIdGenerator",
    "IdGenerator",
    "IntegrityMetadata",
    "PrefixedUuidGenerator",
    "Principal",
    "PrincipalType",
    "RedactionError",
    "RedactionPolicy",
    "ResourceType",
    "Sensitivity",
    "Source",
    "SystemClock",
    "TrustLevel",
    "VerificationStatus",
    "capture_bytes",
    "capture_string",
    "deterministic_json_bytes",
    "event_from_json",
    "event_to_dict",
    "parse_event",
    "serialize_event",
    "serialize_event_for_persistence",
]
