"""Domain primitives for ActionLineage evidence."""

from actionlineage.domain.canonicalization import (
    CANONICALIZATION_VERSION,
    PLANNED_CANONICALIZATION_VERSION,
    SUPPORTED_PERSISTED_EVENT_CANONICALIZATIONS,
    CanonicalizationError,
    is_supported_persisted_event_canonicalization,
    persisted_event_canonicalization_policy,
    require_supported_persisted_event_canonicalization,
)
from actionlineage.domain.events import (
    DEFAULT_JSON_MAX_ARRAY_LENGTH,
    DEFAULT_JSON_MAX_DEPTH,
    DEFAULT_JSON_MAX_OBJECT_MEMBERS,
    SPEC_VERSION,
    Causality,
    Classification,
    Correlation,
    CorroborationType,
    EventEnvelope,
    EventType,
    EvidenceLink,
    EvidenceRelationship,
    IntegrityMetadata,
    Principal,
    PrincipalType,
    ResourceType,
    Sensitivity,
    Source,
    TrustLevel,
    VerificationStatus,
)
from actionlineage.domain.ids import FixedIdGenerator, IdGenerator, PrefixedUuidGenerator
from actionlineage.domain.redaction import (
    CaptureMetadata,
    RedactionError,
    RedactionPolicy,
    capture_bytes,
    capture_string,
)
from actionlineage.domain.serialization import (
    deterministic_json_bytes,
    event_from_json,
    event_to_dict,
    parse_event,
    serialize_event,
    serialize_event_for_persistence,
)
from actionlineage.domain.time import Clock, FixedClock, SystemClock

__all__ = [
    "CANONICALIZATION_VERSION",
    "DEFAULT_JSON_MAX_ARRAY_LENGTH",
    "DEFAULT_JSON_MAX_DEPTH",
    "DEFAULT_JSON_MAX_OBJECT_MEMBERS",
    "PLANNED_CANONICALIZATION_VERSION",
    "SPEC_VERSION",
    "SUPPORTED_PERSISTED_EVENT_CANONICALIZATIONS",
    "CanonicalizationError",
    "CaptureMetadata",
    "Causality",
    "Classification",
    "Clock",
    "Correlation",
    "CorroborationType",
    "EventEnvelope",
    "EventType",
    "EvidenceLink",
    "EvidenceRelationship",
    "FixedClock",
    "FixedIdGenerator",
    "IdGenerator",
    "IntegrityMetadata",
    "PrefixedUuidGenerator",
    "Principal",
    "PrincipalType",
    "RedactionError",
    "RedactionPolicy",
    "ResourceType",
    "Sensitivity",
    "Source",
    "SystemClock",
    "TrustLevel",
    "VerificationStatus",
    "capture_bytes",
    "capture_string",
    "deterministic_json_bytes",
    "event_from_json",
    "event_to_dict",
    "is_supported_persisted_event_canonicalization",
    "parse_event",
    "persisted_event_canonicalization_policy",
    "require_supported_persisted_event_canonicalization",
    "serialize_event",
    "serialize_event_for_persistence",
]
