"""Optional service mode helpers."""

from actionlineage.service.api import ServiceDependencyError, create_app
from actionlineage.service.auth import (
    JwtAuthenticator,
    JwtLibraryUnavailable,
    OidcJwtAuthenticator,
    ServiceAuthError,
    ServiceCapability,
    ServicePrincipal,
    ServiceRole,
    StaticTokenAuthenticator,
    require_capability,
    require_role,
)
from actionlineage.service.health import HealthIssue, HealthReport, HealthState, check_local_health
from actionlineage.service.runtime import (
    DEFAULT_DATABASE_PATH,
    DEFAULT_EXPORT_ROOT,
    DEFAULT_JOURNAL_PATH,
    ServiceRuntimeConfigError,
    create_service_app_from_env,
)
from actionlineage.service.tenancy import (
    ServiceTenant,
    TenantAccessDecision,
    TenantIsolationError,
    TenantRegistry,
    TenantRoleBinding,
    TenantStorageLayout,
    TenantStorageScope,
    confined_service_path,
    require_tenant_role,
    require_tenant_storage_scope,
    validate_tenant_id,
)

__all__ = [
    "DEFAULT_DATABASE_PATH",
    "DEFAULT_EXPORT_ROOT",
    "DEFAULT_JOURNAL_PATH",
    "HealthIssue",
    "HealthReport",
    "HealthState",
    "JwtAuthenticator",
    "JwtLibraryUnavailable",
    "OidcJwtAuthenticator",
    "ServiceAuthError",
    "ServiceCapability",
    "ServiceDependencyError",
    "ServicePrincipal",
    "ServiceRole",
    "ServiceRuntimeConfigError",
    "ServiceTenant",
    "StaticTokenAuthenticator",
    "TenantAccessDecision",
    "TenantIsolationError",
    "TenantRegistry",
    "TenantRoleBinding",
    "TenantStorageLayout",
    "TenantStorageScope",
    "check_local_health",
    "confined_service_path",
    "create_app",
    "create_service_app_from_env",
    "require_capability",
    "require_role",
    "require_tenant_role",
    "require_tenant_storage_scope",
    "validate_tenant_id",
]
