apiVersion: v1
kind: Secret
metadata:
  name: {{ include "actionlineage.fullname" . }}-token
  labels:
    {{- include "actionlineage.labels" . | nindent 4 }}
type: Opaque
stringData:
  ACTIONLINEAGE_SERVICE_TOKEN: {{ .Values.serviceRuntime.token | quote }}
